[build]
builder = "nixpacks"

[deploy]
preDeployCommand = ["python photoalbum/manage.py migrate"]
startCommand = "gunicorn photoalbum.wsgi:application --bind 0.0.0.0:8000"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always" 