# Generated by Django 4.2.20 on 2025-03-19 19:21

import albums.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Fénykép neve')),
                ('image', models.ImageField(upload_to=albums.models.get_upload_path, verbose_name='Kép')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Feltöltés dátuma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fénykép',
                'verbose_name_plural': 'Fényképek',
                'ordering': ['-upload_date'],
            },
        ),
    ]
