# Generated by Django 4.2.7 on 2025-05-05 20:52

import albums.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, verbose_name='Leírás'),
        ),
        migrations.AddField(
            model_name='photo',
            name='detected_persons',
            field=models.IntegerField(default=0, verbose_name='Észlelt személyek száma'),
        ),
        migrations.AddField(
            model_name='photo',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to=albums.models.get_upload_path, verbose_name='Feldolgozott kép'),
        ),
    ]
