# Generated by Django 4.2.7 on 2025-05-07 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albums', '0003_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fénykép értesítés',
                'verbose_name_plural': 'Fénykép értesítések',
            },
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
